### ISSUE TITLE
Non-recoverable error when signals present on wire.

### ISSUE THREAD

**Issue by kaufman-bryce** [justarandomgeek/factorio-magic-lamp#1]
Factorio 0.17.53
https://puu.sh/DNxLV/98a3b55910.png

The mod Magic Lamp caused a non-recoverable error.
Please report this error to the mod author.

Error while running event magic-lamp::on_tick (ID 0)
__magic-lamp__/control.lua:94: attempt to index field 'signal' (a nil value)
stack traceback:
	__magic-lamp__/control.lua:94: in function 'get_signals_filtered'
	__magic-lamp__/control.lua:131: in function 'on_tick_numeric_lamp'
	__magic-lamp__/control.lua:277: in function 'on_tick_lamp'
	__magic-lamp__/control.lua:296: in function <__magic-lamp__/control.lua:284

Steps to reproduce:
-Place Magic Lamp
-Connect wire to constant combinator.
-Set any value on any signal in combinator.

Wires can be connected when they have no data, but will crash as soon as any signal has a value.

**Comment by justarandomgeek** [comment]
fixed in 0.17.6
